### ISSUE TITLE
ACCT ACTIVITY is not able to works

### ISSUE THREAD

**Issue by weikhor** [tylerebowers/Schwab-API-Python#14]
When order trade is executed, activity is not being notified in streaming data api

**Comment by tylerebowers** [comment]
What keys/fields are you using?
This may be a Schwab issue instead.

**Comment by tylerebowers** [comment]
Fixed in pypi 1.9.8
Default command "ADD" is not a valid option for account activity, changed default to "SUBS"

To update: `pip install schwabdev --upgrade`
