### ISSUE TITLE
2 second  timeout for requests is too agressive

### ISSUE THREAD

**Issue by arstone** [tylerebowers/Schwab-API-Python#15]
I ran into a timeout today when making an API request.  I see the 2-second timeout and think it is too aggressive.

Can we add a request_timeout class variable in the client and give it a longer timeout? Maybe 10 seconds?

I can create a pull request if you would like.  

This is excellent work, Tyler. Thank you.

**Comment by tylerebowers** [comment]
In pypi 2.0.2:
*default request timeout changed to 5 sec
*custom timeout can be set at client initialization, i.e. `client = schwabdev.Client("app key", "app secret", timeout=10)`
