### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED - self-signed certificate in certificate chain error when connecting to streaming server

### ISSUE THREAD

**Issue by dereknguyenio** [tylerebowers/Schwab-API-Python#17]
### Issue Description
Hello,

I'm encountering an SSL certificate verification issue when trying to connect to the streaming server using the Schwab API. Here are the details:

### Environment
- **OS**: macOS 
- **Python Version**: 3.12.4
- **schwabdev Version**: Latest from GitHub

### Code Snippet
```python
import schwabdev
from dotenv import load_dotenv
import os

def main():
    client = schwabdev.Client(os.getenv('app_key'), os.getenv('app_secret'), os.getenv('callback_url'))
    client.update_tokens_auto()  # update tokens automatically (except refresh token)

    # example of using the default response handler
    client.stream.start()

    client.stream.send(client.stream.level_one_equities("AMD", "0,1,2,3,4,5,6,7,8"))

    # stop the stream after 60 seconds (since this is a demo)
    import time
    time.sleep(60)
    client.stream.stop()

if __name__ == '__main__':
    print("Welcome to the unofficial Schwab interface!\nGithub: https://github.com/tylerebowers/Schwab-API-Python")
    load_dotenv()
    main() 

```

### Error Message

```[INFO]: Access token last updated: 2024-06-22 12:25:21 (expires in 814 seconds)
[INFO]: Refresh token last updated: 2024-06-21 10:29:02 (expires in 6 days)
[INFO]: Linked Accounts:
[INFO]: Initialization Complete
[INFO]: Connecting to streaming server -> [ERROR]: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)
[ERROR]: Stream not alive for more than 1 minute, exiting...
[WARN]: Stream is not active, request queued.
```

### Steps to Reproduce

Clone the repository.
Set up the environment with the required API keys and secrets.
Run the provided code snippet.

Could you please provide guidance on how to properly configure the SSL certificate validation or any workaround for this issue?

**Comment by tylerebowers** [comment]
Please check your system clock and make sure that your time is synced.
You may have to install the pip packages pip-system-certs.

**Comment by tylerebowers** [comment]
Actually it appears that on MacOS you need to run a certificates installer. For you the command should be:
`open /Applications/Python\ 3.12/Install\ Certificates.command`

**Comment by dereknguyenio** [comment]
This wo

> Actually it appears that on MacOS you need to run a certificates installer. For you the command should be: `open /Applications/Python\ 3.12/Install\ Certificates.command`

This worked perfectly, thank you!
