### ISSUE TITLE
Problem streaming data on Mac OS

### ISSUE THREAD

**Issue by reggievrandolph** [tylerebowers/Schwab-API-Python#18]
Getting this error when trying to stream on mac, I'm pretty sure this was working on PC. Just got a Mac.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'API misuse: setting the main menu on a non-main thread. Main menu contents should only be modified from the main thread.'

Thoughts on possible fixes. Thanks.

**Comment by tylerebowers** [comment]
Which version of the code is this? Update to the latest version first if you have not already.

**Comment by reggievrandolph** [comment]
Version schwabdev==1.0.1. Is there another version?

**Comment by tylerebowers** [comment]
> Version schwabdev==1.0.1. Is there another version? 

Yes, the current version is 2.1.1
'pip install schwabdev --upgrade'

**Comment by reggievrandolph** [comment]
Ha got it working, for some reason I had downloaded an older version of python, which caused me to only be able to download an older version of schwabdev. Thanks.
