### ISSUE TITLE
paper trading in sandbox env?

### ISSUE THREAD

**Issue by ck0099** [tylerebowers/Schwab-API-Python#20]
RE: paper trading in sandbox env?

There seems to be a sandbox env for api, how can we make use of it to paper trade? or at least test out the API before live trading?

https://developer.schwab.com/user-guides/apis-and-apps/test-in-sandbox

**Comment by tylerebowers** [comment]
I have heard of the sandbox enviroment. But I believe it refers to the testing that you can perform on the website: "Sandbox testing provides visibility of inputs/outputs, or requests/responses, of data for each call. The data is rendered and persists within this module's UI until the next call is run. " And I don't think that the sandbox can be used for paper trading.

I have, however, been considering several approaches to a paper trading capable client.

**Comment by tylerebowers** [comment]
You could email them and ask
