### ISSUE TITLE
Should the auth token timestamps have time zone info?

### ISSUE THREAD

**Issue by simonque** [tylerebowers/Schwab-API-Python#22]
The code that I'm using checks against the "refresh_token_issued" field to report how much time is remaining until expiration. It would be convenient to have a timezone field for this, esp as my local system on which I do development is not always in the same time zone as the fixed-time zone Docker image that I'm running in the cloud.

I can submit a pull request if you think this is a good idea.

**Comment by tylerebowers** [comment]
Yes, in the next update I will be moving to UTC for the tokens.json date format. In addition internal workings will be moving away from deprecated datetime functions in favor of timezone aware objects.
