### ISSUE TITLE
Use of Deprecated `utcnow()` and `utcfromtimestamp()` APIs

### ISSUE THREAD

**Issue by ShreyTiwari** [tylerebowers/Schwab-API-Python#23]
## Summary
The codebase currently uses `datetime.utcnow()` or `datetime.utcfromtimestamp()`, which are deprecated and will not work with Python 3.12. These APIs can lead to bugs due to their handling of naïve datetimes. Transitioning to time zone-aware alternatives is recommended.

## CodeQL generated alerts:
1. Location: /examples/api_demo.py
   Line: 39
   Column: 51-67
   Deprecated Call: utcnow

2. Location: /examples/api_demo.py
   Line: 39
   Column: 91-107
   Deprecated Call: utcnow

3. Location: /examples/api_demo.py
   Line: 67
   Column: 43-59
   Deprecated Call: utcnow

4. Location: /examples/api_demo.py
   Line: 67
   Column: 83-99
   Deprecated Call: utcnow

5. Location: /examples/api_demo.py
   Line: 79
   Column: 45-61
   Deprecated Call: utcnow

6. Location: /examples/api_demo.py
   Line: 79
   Column: 85-101
   Deprecated Call: utcnow

## Explanation
**Issue:**
- `datetime.utcnow()` and `datetime.utcfromtimestamp()` return naïve datetimes (without time zone info).
- In Python 3, naïve datetimes are interpreted as system-local times, causing inconsistencies.
- These methods are deprecated and no longer work in Python 3.12.

**Example Problem:**
```python
from datetime import datetime
ts = 1571595618.0
x = datetime.utcfromtimestamp(ts)
x_ts = x.timestamp()
assert ts == x_ts, f"{ts} != {x_ts}" # Can fail in non-UTC locales
```
**Recommended Solution:**
Switch to time zone-aware methods:
```python
from datetime import datetime, timezone
# Replace utcnow()
dt_now = datetime.now(tz=timezone.utc)
# Replace utcfromtimestamp()
ts = 1571595618.0
x = datetime.fromtimestamp(ts, tz=timezone.utc)
x_ts = x.timestamp()
assert ts == x_ts, f"{ts} != {x_ts}" # This succeeds
```
## Action Required:
- Replace all instances of `datetime.utcnow()` with `datetime.now(tz=timezone.utc)`.
- Replace all instances of `datetime.utcfromtimestamp()` with `datetime.fromtimestamp(ts, tz=timezone.utc)`.

## References:
For more details, see:
- https://blog.ganssle.io/articles/2019/11/utcnow.html
- https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
	
Thank you,
Shrey

**Comment by tylerebowers** [comment]
Yes, I have already done this for the next update and am also changing the format for tokens.json(). Someone else also asked something similar in #22.
