### ISSUE TITLE
How to obtain historical option chains and view past option chain information

### ISSUE THREAD

**Issue by victorxys** [tylerebowers/Schwab-API-Python#24]
Due to the needs of data analysis, I had to view the detailed information of a certain historical option, minute-by-minute quotes, and major information such as Delta and Gamma.
Thanks

**Comment by tylerebowers** [comment]
Schwab does not offer price history for option contracts. You can either build your own backlog by streaming the contracts you want, or find/purchase option contract history.

**Comment by victorxys** [comment]
> Schwab does not offer price history for option contracts. You can either build your own backlog by streaming the contracts you want, or find/purchase option contract history.

Yes I've just recorded the contracts by streaming. Thanks a lot for this API.
