### ISSUE TITLE
The refresh token times out 1 day sooner than necessary.

### ISSUE THREAD

**Issue by itcd** [tylerebowers/Schwab-API-Python#27]
On lines 108 to 110 of [api.py](https://github.com/tylerebowers/Schwab-API-Python/blob/main/schwabdev/api.py):
        if (datetime.datetime.now(datetime.timezone.utc) - self._refresh_token_issued).days >= (self._refresh_token_timeout - 1) or force:  # check if we need to update refresh (and access) token
            print("[Schwabdev] The refresh token has expired, please update!")
            self._update_refresh_token()

For example, if we set
_refresh_token_timeout=7
_refresh_token_issued=datetime.datetime.fromisoformat('2024-09-21T03:59:00.000000+00:00')
and assume
datetime.datetime.now(datetime.timezone.utc) is 2024-09-27 04:00:00.000000+00:00
In this case, only 6 days have passed since the refresh token was issued, meaning it is still valid.

However, the condition
(datetime.datetime.now(datetime.timezone.utc) - _refresh_token_issued).days >= (_refresh_token_timeout - 1)
evaluates to True, which causes the refresh token to timeout 1 day sooner than necessary.
Therefore, self._refresh_token_timeout - 1 should be changed to self._refresh_token_timeout on line 108.

**Comment by tylerebowers** [comment]
Releasing new update tonight that will warn the user when the refresh token has less than 12 hours remaining, and will initialize a refresh token update when 1 hour is remaining. This code is a bit legacy from the conversion from TDA where the refresh was valid for 90 days.

**Comment by tylerebowers** [comment]
Changed in PyPI 2.2.5. User will be notified 12 hours before refresh token expires. Refres token update function will be run 1 hour before it expires.
