### ISSUE TITLE
Streamer Error

### ISSUE THREAD

**Issue by nam777** [tylerebowers/Schwab-API-Python#28]
Welcome to The Unofficial Schwab Python Wrapper!
Github: https://github.com/tylerebowers/Schwab-API-Python
Streaming documentation: https://github.com/tylerebowers/Schwab-API-Python/blob/master/docs/stream.md
Access token last updated: 2024-09-27 16:35:51 (expires in 1386 seconds)
Refresh token last updated: 2024-09-27 14:31:12 (expires in 7 days)
Schwabdev Client Initialization Complete
Connecting to streaming server...
Stream is not active, request queued.
**_Stream has crashed within 90 seconds, likely no subscriptions or invalid login._**
Stream is not active, request queued.

I am receiving a crash error.  When I look at the source code, I can't determine what the issue is.  My app is set up and I am able to access the account info API with no issues.  Any thoughts on the error?   I am not making any calls to create the subscription as the error is being trigger on the following:

`streamer.start()`

Note: I am able to make a call for a basic quote successfully.

`print(client.quote("AAPL").json())`

**Comment by tylerebowers** [comment]
Update to the latest version of Schwabdev first `pip install schwabdev --upgrade`

**Comment by nam777** [comment]
> Update to the latest version of Schwabdev first `pip install schwabdev --upgrade`

I am still receiving the same answer.  Any other ideas?

**Comment by tylerebowers** [comment]
Are you on a Mac? If so you need to install the certificates for python. After you install python it tells you to run this command, many people miss it. It installs certificates that are important for python to use for ssl networking.

`open /Applications/Python\ 3.12/Install\ Certificates.command`

If you have python 3.11 change accordingly.

**Comment by luckman212** [comment]
@tylerebowers What if we installed Python3 via Homebrew? Is there a particular module we need to install via pip to the global `site-packages` dir?

**Comment by tylerebowers** [comment]
I believe the installation command is the same, however I could be wrong. https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate

**Comment by tylerebowers** [comment]
Did this fix your issue? This is more of an issue with your local configuration. You need to install the python certificates.

**Comment by tylerebowers** [comment]
Going to close this for non-response and assuming that one of the suggested fixes works. There are also many other fixes suggested online. This is not a problem with the schwabdev package.
