### ISSUE TITLE
api.orders.getOrders() does not return any output

### ISSUE THREAD

**Issue by fanflx** [tylerebowers/Schwab-API-Python#3]
I have run the exact code in main.py, and above function only returns None.
The setup and authorization works fine, and following codes runs perfect:

accountNumbers = api.accounts.accountNumbers()
universe.credentials.encryptedId = accountNumbers[0].get('hashValue')
I got correct accountNumbers and encryptedId.
so, what could go wrong here?

**Comment by tylerebowers** [comment]
Noted. Looking into it.

**Comment by fanflx** [comment]
I have tried to use following code to change the string format into: yyyy-MM-dd'T'HH:mm:ss.SSSZ:
fromEnteredTime.strftime('%Y-%m-%d\'T\'%H:%M:%S.%f')[:-3] + 'Z'
But still got None as output.

**Comment by fanflx** [comment]
actually, the code should be (escape for 'T'): 
fromEnteredTime.strftime('%Y-%m-%d\'T\'%H:%M:%S.%f')[:-3] + 'Z'

**Comment by fanflx** [comment]
just print out 'response' from: _ResponseHandler(response)
it turns out <Response [401]>: An error message indicating either authorization token is invalid or there are no accounts the caller is allowed to view or use for trading that are registered with the provided third party application
I assume authorization token and accountNumber is correct, as it is retrieved sucessfully with following code with out any problem:
accountNumbers = api.accounts.accountNumbers()
universe.credentials.encryptedId = accountNumbers[0].get('hashValue')

**Comment by fanflx** [comment]
Finally, found the solution:
1. change the time string format to following: (this should apply to all the api functions that need this format - might need to revise _TimeConvert())
    toEnteredTime.strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z'   -- (assume toEnteredTime assigned by datetime.now() format)
2. pass the hashvalue of account number directly to getOrders():
    current way of pass value of encryptedId seems not working, getOrders() does not pice up accountNumber through "accountNumber=universe.credentials.encryptedId", guess this is due to different scopes. following code seems fix this problem:
    
accountNumbers = api.accounts.accountNumbers()
acct_num = accountNumbers[0].get('hashValue')
orders = api.orders.getOrders(3000, datetime.now()-timedelta(days=7), datetime.now(), accountNumber=acct_num)

**Comment by fanflx** [comment]
Finally, found the solution:

1. Change the time string format, using toEnteredTime as example: (this should apply to all the api functions that need this format - might need to revise _TimeConvert())

```
current_time = datetime.now()
toEnteredTime = current_time.strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z' 
```
pass the hashvalue of account number directly to getOrders():
current way of passing value of encryptedId seems not working, getOrders() does not pick up the hash value of accountNumber through "accountNumber=universe.credentials.encryptedId", guess this is due to different scopes. following code seems fixed this problem:
```
accountNumbers = api.accounts.accountNumbers()
acct_num = accountNumbers[0].get('hashValue')
orders = api.orders.getOrders(3000, datetime.now()-timedelta(days=7), datetime.now(), accountNumber=acct_num)
```

**Comment by tylerebowers** [comment]
Fixed in latest update with a variation of your proposed fix.
