### ISSUE TITLE
python notebook not working.

### ISSUE THREAD

**Issue by daskabe** [tylerebowers/Schwab-API-Python#30]
I installed the schwabdev module and i cant seem to use the Client class.  Intellisense seems to find info about it but running it causes error. I have updated .env file.

![Screenshot 2024-10-04 at 12 44 47 PM](https://github.com/user-attachments/assets/2e79a38a-a660-4d1c-83e7-89c26ba42df7)

Also i would be nice to have example notebook that references the library directly so i want to add features i can modify the library directly. 

thank you for this library.

**Comment by tylerebowers** [comment]
Schwabdev is compatible with Python 3.11 and above so you couldn't have installed it to that python version.

**Comment by daskabe** [comment]
its not working using python 3.11 in vs code.

Im relatively new to python projects. But im not sure how module is resolved without stating the path to schwabdev folder as you suggested.

![Screenshot 2024-10-05 at 4 28 10 PM](https://github.com/user-attachments/assets/7ae76546-8268-4fb3-9883-d83a73ebbf62)

chatgpt suggested i do the following. But then im getting other missing packages for websockets.

```

import dotenv
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from schwabdev import api, stream
```
![Screenshot 2024-10-05 at 5 05 43 PM](https://github.com/user-attachments/assets/38d9f7cf-25a5-4fe7-b519-3af1ba3053fd)


i created this requirements.txt file and still get the `ModuleNotFoundError: No module named 'websockets' error after installation.

requirements.txt
```
python-dotenv==1.0.1
Requests==2.32.3
setuptools==68.2.2
websockets==13.
websocket-client==1.2.1
schwabdev==2.2.6

```

**Comment by tylerebowers** [comment]
Try launching Jupyter from the terminal instead of through VSCode. For me the notebook worked in PyCharm and VScode.

**Comment by tylerebowers** [comment]
Are the normal .py files working?

**Comment by daskabe** [comment]
yes, if i take the jupyter notebook and .env file and put them in separate folder and install schwabdev via pip; it works. 
I opened it in vscode and using 3.11 python.

**Comment by tylerebowers** [comment]
Ok, great! Closing issue.
