### ISSUE TITLE
Support for Equity Awards accounts

### ISSUE THREAD

**Issue by manishbajpai** [tylerebowers/Schwab-API-Python#32]
In the schwabdev.Client() call, when we are taken to Schwab website, we are presented with an option to authorize the access to all the accounts. Unfortunately, equity awards accounts are missing from this list. So it is not possible to get access to them. This is not a bug of schwabdev package, but rather the way Schwab website works, because I have the same observation with my quicken software. This is a new feature request to add support for equity awards accounts.
My understanding is that equity award accounts are treated different than other accounts by Schwab and there is perhaps a different url to authorize them. 
This is the link to equity award center: https://eac.schwab.com/

**Comment by tylerebowers** [comment]
Hello Manish, this is a python wrapper that will access the Schwab API, it is an independent tool which is is not affiliated with or endorsed by Schwab. If you would like this feature to be added you will have to contact Schwab, specifically their api team at: `traderapi@schwab. com`

**Comment by manishbajpai** [comment]
>>is an independent tool which is is not affiliated with or endorsed by Schwab.
I understand, but I’m wondering if there might be a different Line of Business (LOB) API required for EAC access. To clarify, I’m not affiliated with Schwab; I’m simply trying to use this API as a developer. I’ll reach out to traderapi@schwab.com, though if it’s related to a different LOB, they may not be able to assist. Unfortunately, obtaining the API documentation requires LOB approval, so it could take some time to figure out.

Thank you for your insights.
