### ISSUE TITLE
Error while authenticating

### ISSUE THREAD

**Issue by manojjenago** [tylerebowers/Schwab-API-Python#33]
Hi Getting error while authenticating. the URL that opens give the below error. Please suggest.

![image](https://github.com/user-attachments/assets/3cf4f229-ffb5-4659-9bcf-72268dbf21a9)

**Comment by tylerebowers** [comment]
Problem: Trying to sign into account and get error message: "We are unable to complete your request. Please contact customer service for further assistance."
Problem: "Whitelabel Error Page This application has no configured error view, so you are seeing this as a fallback." (status=500)
Fix: Your app is "Approved - Pending", you must wait for status "Ready for Use".
Note: Or you could have an account type that is not supported by the Schwab API.
In docs: https://github.com/tylerebowers/Schwab-API-Python/blob/main/docs/client.md

**Comment by manojjenago** [comment]
> Problem: Trying to sign into account and get error message: "We are unable to complete your request. Please contact customer service for further assistance." Problem: "Whitelabel Error Page This application has no configured error view, so you are seeing this as a fallback." (status=500) Fix: Your app is "Approved - Pending", you must wait for status "Ready for Use". Note: Or you could have an account type that is not supported by the Schwab API. In docs: https://github.com/tylerebowers/Schwab-API-Python/blob/main/docs/client.md

Thanks for your quick response.
