### ISSUE TITLE
api_demo.py demo fails

### ISSUE THREAD

**Issue by dmurray2413** [tylerebowers/Schwab-API-Python#37]
getting toes wet with SchwabAPI. 
I have a developer account, test application, and app key and secret.
Created simple web page using IIS.
updated .env with provided app key and app secret.

upon testing, apparently, the return URL from Schwab is not in the expected format.
Recommendations?

Test session recorded and available for view at:
https://www.youtube.com/watch?v=3h0hB0mOo54

**Comment by tylerebowers** [comment]
Your app status is "Approved - Pending", you must wait for status "Ready for Use".

**Comment by dmurray2413** [comment]
Yeah.  My bad . late night. Figured it out about 3am.  Did a Home ‘DOH!!!’ realized the time and went to bed

**Comment by tylerebowers** [comment]
Ok, closing issue.
