### ISSUE TITLE
How to check the options details of Futures?

### ISSUE THREAD

**Issue by xuqiantong** [tylerebowers/Schwab-API-Python#38]
For example, I want to query the option chain of futures /ES. What symbol should I put to the API calls? If I simply provide "ES", it directs me to the stock ES, rather than the futures.

**Comment by tylerebowers** [comment]
Someone else was wondering the same thing, this was the Schwab API team's response: "Hello, Thank you for reaching out to the Schwab Trader API Support Team. The GET /chains endpoint does not currently support data for options on futures. At this time, it will only return data for equity and index options."

Also, futures typically follow this format: 
Key format: '/' + 'root symbol' + 'month code' + 'year code'
Month code is 1 character: (F: Jan, G: Feb, H: Mar, J: Apr, K: May, M: Jun, N: Jul, Q: Aug, U: Sep, V: Oct, X: Nov, Z: Dec)
Year code is 2 characters (i.e. 2024 = 24)
Key examples: "/ESF24", "/GCG24", "/ES"

**Comment by xuqiantong** [comment]
I see. Thanks a lot @tylerebowers!
