### ISSUE TITLE
Access Token not refreshed - 400 Bad Reques t- unsupported_token_type

### ISSUE THREAD

**Issue by NealWalters** [tylerebowers/Schwab-API-Python#40]
Our code works fine for 30 minutes, (we logon and run out code multiple times), then access token expires, then I get this. 
[Another guy runs the code in Poland, and it works perfectly fine. ]

INFO:Schwabdev.Tokens:The access token has expired, updating automatically.
ERROR:Schwabdev.Tokens:{"error":"unsupported_token_type","error_description":"400 Bad Request: \"{\"error_description\":\"Exception while authenticating refresh token [tokenDigest=R8QKLpffOFVUJuvqbJ0\/1RNzqtrrnXrtTqQ6bCiRCMw=, Exception=Failed refresh token authentication [tokenDigest=R8QKLpffOFVUJuvqbJ0\/1RNzqtrrnXrtTqQ6bCiRCMw=]]\",\"error\":\"refresh_token_authentication_error\"}\""}
ERROR:Schwabdev.Tokens:Could not get new access token; refresh_token likely invalid.
INFO:Schwabdev.Tokens:Access token expires in -00H:19M:45S
INFO:Schwabdev.Tokens:Refresh token expires in 167H:10M:14S
INFO:Schwabdev.Tokens:The access token has expired, updating automatically.
INFO:Schwabdev.Client:Client Initialization Complete

Further, shouldn't this be a fatal error?  Should we check that our client variable is None before continuing? 
Because any calls we make to client after this fail. 

Thanks!

**Comment by NealWalters** [comment]
I'm in Texas, the other programmer is in Poland.  So I was thinking, just maybe it is a date/time or UTC type issue.

**Comment by tylerebowers** [comment]
> I'm in Texas, the other programmer is in Poland. So I was thinking, just maybe it is a date/time or UTC type issue. I allowed him to logon to my Schwab account to test. So now I'm thinking that the second person to logon gets a new 7 day refresh token, which invalids the other guys? But today, I was the last to logon, and his works and mine fails.
> 
> Update: A few hours ago, I deleted token.json, went through signon again, and it worked beyond 30 minutes. I asked the guy in Poland to try, and now he is getting the error. So apparently, it is because two of us are trying to use the same refresh token.

Yes, There can only be one valid refresh token at a time. In other words, if you have the code running on one system, then on another system sign in to the account for the app,  the refresh token on the original system is now invalidated and cannot be used to generate a new access token. You can also think of it like: a new sign-in will invalidate *ALL* other refresh tokens so now you have the only valid one.

**Comment by tylerebowers** [comment]
Closing this issue.
