### ISSUE TITLE
websocket connection issue

### ISSUE THREAD

**Issue by fanflx** [tylerebowers/Schwab-API-Python#6]
I got errors from stream.startManual() when run following code:
```
if __name__ == '__main__':
    api.initialize()  # checks tokens & loads variables
    api.updateTokensAutomatic() # starts thread to update tokens automatically
    stream.startManual() # start the stream manually
```
The output message:
```
[INFO]: Access token last updated: 2024-04-18 11:57:00
[INFO]: Refresh token last updated: 2024-04-17 19:08:14
[INFO]: The access token has expired, updating automatically.
[INFO]: Access token updated: 2024-04-18 12:31:52.959456
[WARN]: Access token expires in 1799 seconds!
[WARN]: Refresh token expires in 7 days!
[INFO]: Initialization Complete
[ERROR]: can't register atexit after shutdown
[ERROR]: Stream not alive for more than 1 minute, exiting...
```
the streamVars.terminal pops up and instantly closed. 
I checked in _start() function, everything is fine until: (all streamVars looks normal to me)
```
async with websockets.connect(streamVars.streamerInfo.get('streamerSocketUrl'),
                                          ping_interval=None) as streamVars.webSocket:
```
besides normall accessToken, do I need to apply for any special permission from Charles Schwab for websocket stream?

**Comment by tylerebowers** [comment]
Havent had this issue, but streaming is not supported by Schwab so it is possible that dev accounts made after were not given access yet. You could also try asking people on the discord: https://discord.gg/m7SSjr9rs9

**Comment by tylerebowers** [comment]
Schwab doesn't support streaming (officially) so going to close this. Youu could also be running an outdated version of the repo.
