### ISSUE TITLE
Move secrets to env file

### ISSUE THREAD

**Issue by enorms** [tylerebowers/Schwab-API-Python#7]
I noticed you are using a hard coded key and secret in `universe.py` and I modified the code to use a `.env` file and then gitignore it so that there is no chance of accidentally committing to a repo. Would you like me submit a PR to integrate into your code base?

So instead of 
```
class credentials:
    appKey = "Your App Key"
    appSecret = "Your App Secret"
```
it's now
```
import os
from dotenv import load_dotenv

load_dotenv()

class credentials:
    appKey = os.getenv("APP_KEY")
    appSecret = os.getenv("APP_SECRET")
```

and there's a `.env` with 
```
APP_KEY=<key>
APP_SECRET=<secret>
```

And in gitignore add `.env`

**Comment by tylerebowers** [comment]
I have a seperate (private) repo which I use for personal development. I did think about using a .env but not using it is easiest for the end user.
